server:
  port: 8080
  servlet:
    context-path: /core

spring:
  application:
    name: webparserapi-core
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: windows-1251
      enabled: true
      force: true

logging:
  level:
    root: INFO
    ru.olgrin.core: debug