server:
  port: 8082
  servlet:
    context-path: /infrastructure
    encoding:
       charset: UTF-8
       enabled: true
       force: true

spring:
  application:
    name: webparserapi-infrastructure
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        enabled: true
        temperature: 1
        max-completion-tokens: 1000
        options:
          model: gpt-4o
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small
qdrant:
  host: localhost
  port: 6334
  api-key: ""
  collection-name: "test_collection"
  use-tls: false
  initialize-schema: true
  use-grpc: true

huggingface:
  token: ${HUGGINGFACE_API_KEY}
  rosberta:
    url: https://router.huggingface.co/hf-inference/models/ai-forever/ru-en-RoSBERTa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/